variables:
  rgName: 'lp22-casestudy4-dev'
  location: 'northeurope'
  spnName: 'lp22-casestudy-devops-spn'
  keyVaultName: "kv-casestudy4team4" 
  objectId: "cce97344-5cf4-430d-ad04-fde0bcd06c8a"
resources:
  - repo: self
  
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployKeyVault
  jobs:
  - job: DeployKeyVault
    displayName: "Deploy KeyVault"
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: "Deploy KeyVault"
      inputs:
        azureSubscription: $(spnName)
        resourceGroupName: $(rgName)
        location: $(location)
        csmFile: $(Build.SourcesDirectory)/Modules/KeyVault/keyvaultdeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/Modules/KeyVault/keyvaultdeploy.parameters.json
        overrideParameters: '-keyVaultName $(keyVaultName)
                             -objectId $(objectId)'