variables:
- group: lp22_caseStudy4_VariableGroup
- name: rgName
  value: 'lp22-casestudy4-dev'
- name: location
  value: 'northeurope'
- name: spnName
  value: 'lp22-casestudy-devops-spn'

resources:
  - repo: self
  
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Deployapivmss
  jobs:
  - job: Deployapivmss
    displayName: "Deploy apivmss"
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: "Deploy apivmss"
      inputs:
        azureSubscription: $(spnName)
        resourceGroupName: $(rgName)
        location: $(location)
        csmFile: $(Build.SourcesDirectory)/Modules/VirtualMachines/apivmssdeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/Modules/VirtualMachines/apivmssdeploy.parameters.json
        overrideParameters: '-virtualNetworkName "vnet-lp22-casestudy4" 
                            -subnetName "snet-api" 
                            -adminPasswordOrKey $(vmAdminPassword)
                            -fileUris $(apiscript) 
                            -blobBaseUri $(blobbaseurl) 
                            -blobSasToken "$(blobsastoken)"'